import '../styles/globals.css'
import Head from 'next/head'
import HeroBanner from '../components/HeroBanner'

function MyApp({ Component, pageProps }) {
  return (
    <div>
    <Head>
      <title>Forrest Dickison Fine Art & Illustration</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <HeroBanner/>
    </main>
    <Component {...pageProps} />
    </div>
  )
}

export default MyApp
