import { client } from '../lib/client'

import Head from 'next/head'
import HeroBanner from '../components/HeroBanner'
import ProductCategories from '../components/ProductCategories'
import Footer from '../components/Footer'

export default function Home({categories}) {
  return (
    <div>
      <Head>
        <title>Forrest Dickison Fine Art & Illustration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroBanner/>
      </main>
      <div>
        <ProductCategories
          categories={categories}
        />
      </div>
      <footer>
        <Footer/>
      </footer>
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = `*[_type == "category"] | order(order){
    _id,
    "imageUrl": image.asset->url,
    title,
    slug,
    description,
    products[]->{tags}
  }`
  const categories = await client.fetch(query)

  return {
    props: {categories}
  }
}