import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Forrest Dickison Fine Art & Illustration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Forrest Dickison Fine Art & Illustration
        </h1>
      </main>
      <footer>
        <h1>Footer</h1>

      </footer>
    </div>
  )
}
